import { loadMeta, saveMeta, saveRun } from './core/save.js';
import { RunController } from './core/run.js';
import { OLIVIA_SKILL_TREE, SKILLS, CHAR_DEFS, COMPANION_PROFILES } from './data/battle-data.js';

const meta=loadMeta(),app=document.querySelector('#app');
const controller=new RunController({meta,onMetaChange:saveMeta,onRunChange:run=>{saveRun(run);render()}});
let hubView='home';
const button=(label,action,extra='')=>`<button data-action="${action}" ${extra}>${label}</button>`;

function canUnlock(node){return !meta.unlocks.skills.includes(node.id)&&node.req.every(id=>meta.unlocks.skills.includes(id))&&meta.currency.notes>=node.cost}
function renderSkillTree(){const nodes=OLIVIA_SKILL_TREE.map(node=>{const skill=SKILLS[node.id],owned=meta.unlocks.skills.includes(node.id),available=canUnlock(node);return `<article class="skill-node ${owned?'owned':available?'available':'locked'}"><span>Tier ${node.tier} · ${node.branch}</span><h3>${skill.name}</h3><p>${skill.desc}</p><small>${owned?'Freigeschaltet ✔':`${node.cost} 📚 · Voraussetzung: ${node.req.length?node.req.map(x=>SKILLS[x]?.name||x).join(', '):'keine'}`}</small>${owned?'':`<button data-skill-unlock="${node.id}" ${available?'':'disabled'}>Freischalten</button>`}</article>`}).join('');app.innerHTML=`<section class="panel apartment"><div class="eyebrow">OLIVIAS SCHREIBTISCH</div><h1>💻 Neurologie-Fortbildung</h1><p>Forschungsnotizen aus Schichten werden permanent in Fähigkeiten investiert. Freigeschaltete Fähigkeiten stehen Olivia in zukünftigen Runs zur Verfügung.</p><h2>📚 ${meta.currency.notes} Forschungsnotizen</h2><div class="skill-grid">${nodes}</div><div class="actions">${button('← Zurück zur Wohnung','hub-home')}</div></section>`}

function renderPartyBuilder(){
 const selected=new Set(meta.partySelection||[]);
 const cards=Object.keys(COMPANION_PROFILES).map(id=>{const c=CHAR_DEFS[id],p=COMPANION_PROFILES[id],unlocked=meta.unlocks.companions.includes(id),chosen=selected.has(id);return `<article class="companion-card ${chosen?'chosen':''} ${unlocked?'':'locked'}"><div class="companion-head"><span class="companion-avatar">${c.emoji}</span><div><h3>${c.name}</h3><small>${c.role}</small></div></div><p>${p.tagline}</p><div class="mini-stats"><span>HP ${c.base.hp}</span><span>MP ${c.base.mp}</span><span>ATK ${c.base.atk}</span><span>DEF ${c.base.def}</span><span>SPD ${c.base.spd}</span></div>${unlocked?`<button data-companion="${id}">${chosen?'Aus Party entfernen':'In Party aufnehmen'}</button>`:`<div class="unlock-note">🔒 ${p.unlock}</div>`}</article>`}).join('');
 app.innerHTML=`<section class="panel apartment"><div class="eyebrow">DIENSTVORBEREITUNG</div><h1>👥 Party zusammenstellen</h1><p>Olivia ist immer gesetzt. Zusätzlich kannst du bis zu <b>vier</b> freigeschaltete Kolleg:innen für die nächste Schicht auswählen.</p><div class="party-cap"><b>🧠 Olivia</b><span>+ ${selected.size}/4 Begleiter gewählt</span></div><div class="companion-grid">${cards}</div><div class="actions">${button('← Zurück zur Wohnung','hub-home')}</div></section>`;
}

function renderHub(){
 if(hubView==='skills'){renderSkillTree();return}if(hubView==='party'){renderPartyBuilder();return}
 const selectedNames=(meta.partySelection||[]).map(id=>CHAR_DEFS[id]?.name).filter(Boolean);
 app.innerHTML=`<section class="panel apartment"><div class="eyebrow">ROGUELITE v0.4 · DEV</div><h1>🏠 Olivias Wohnung</h1><p>Feierabend. Permanente Fortschritte werden hier vorbereitet; jede Schicht baut anschließend einen neuen temporären Build.</p><div class="stats"><div><span>Forschungsnotizen</span><strong>📚 ${meta.currency.notes}</strong></div><div><span>Gestartete Schichten</span><strong>${meta.stats.runsStarted}</strong></div><div><span>Gewonnene Schichten</span><strong>${meta.stats.runsWon}</strong></div><div><span>Verfügbare Begleiter</span><strong>${meta.unlocks.companions.length}/4</strong></div></div><div class="party-preview"><span>Aktuelle Party</span><strong>🧠 Olivia${selectedNames.length?' + '+selectedNames.join(' + '):' · solo'}</strong></div><div class="room-grid"><article>🛏️ <b>Bett</b><small>Nächste Schicht / Story</small></article><article class="clickable" data-action="hub-skills">💻 <b>Schreibtisch</b><small>Olivia-Skilltree & Forschung</small></article><article class="clickable" data-action="hub-party">👥 <b>Dienstplan</b><small>Party für die nächste Schicht wählen</small></article><article>☕ <b>Küche</b><small>Vorbereitung</small></article></div><div class="actions">${button('Schicht beginnen →','start')}</div></section>`;
}
function renderReward(run){const cards=run.pendingReward.map(r=>`<button class="reward-card" data-reward="${r.id}"><span>${r.icon||'✨'}</span><b>${r.name}</b><small>${r.text}</small></button>`).join('');return `<div class="reward-pick"><div class="eyebrow">SCHICHT-UPGRADE</div><h2>Wähle 1 von 3</h2><p>Diese Verbesserung gilt nur für die aktuelle Schicht.</p><div class="reward-grid">${cards}</div></div>`}
function renderRun(){const run=controller.run,room=controller.currentRoom(),route=run.route.map((r,i)=>`<div class="node ${i<run.roomIndex?'done':''} ${i===run.roomIndex?'current':''}"><span>${i+1}</span><b>${r.title}</b><small>${r.type}</small></div>`).join(''),party=run.party.map(c=>`<div class="run-party-card"><b style="color:${c.color}">${c.emoji} ${c.name}</b><small>Lv${c.level} · HP ${c.hp}/${c.maxHp} · MP ${c.mp}/${c.maxMp}</small></div>`).join(''),relics=run.relics.length?run.relics.join(' · '):'noch keine';app.innerHTML=`<section class="panel hospital"><div class="eyebrow">AKTUELLE SCHICHT</div><h1>🏥 Klinikum</h1><p>Run ${run.id} · Raum ${Math.min(run.roomIndex+1,8)}/8 · ☕ ${run.resources.coffee}</p><div class="run-party">${party}</div><p class="relic-line"><b>Run-Upgrades:</b> ${relics}</p>${run.pendingReward?renderReward(run):`<div class="route">${route}</div><div class="encounter"><h2>${room?room.title:'Schicht abgeschlossen'}</h2><p>${room?room.type.toUpperCase():''}</p>${room?button(room.type==='event'?'Event betreten':'JRPG-Kampf betreten','enter'):''}</div>`}<p class="note">v0.4: Hub-Partywahl, Companion-Unlocks und JRPG-Roguelite-Builds.</p></section>`}
function render(){controller.run?renderRun():renderHub()}
function unlockSkill(id){const node=OLIVIA_SKILL_TREE.find(x=>x.id===id);if(!node||!canUnlock(node))return;meta.currency.notes-=node.cost;meta.unlocks.skills.push(id);saveMeta(meta);render()}
function toggleCompanion(id){if(!meta.unlocks.companions.includes(id))return;const current=new Set(meta.partySelection||[]);if(current.has(id))current.delete(id);else{if(current.size>=4)return;current.add(id)}meta.partySelection=[...current];saveMeta(meta);render()}

document.addEventListener('click',async e=>{
 const unlock=e.target.closest('[data-skill-unlock]')?.dataset.skillUnlock;if(unlock){unlockSkill(unlock);return}
 const companion=e.target.closest('[data-companion]')?.dataset.companion;if(companion){toggleCompanion(companion);return}
 const reward=e.target.closest('[data-reward]')?.dataset.reward;if(reward){controller.chooseReward(reward);return}
 const action=e.target.closest('[data-action]')?.dataset.action;
 if(action==='hub-skills'){hubView='skills';render();return}if(action==='hub-party'){hubView='party';render();return}if(action==='hub-home'){hubView='home';render();return}if(action==='start'){hubView='home';controller.start();return}
 if(action==='enter'){const result=await controller.enterCurrentRoom();if(result?.kind==='run-finished')alert(result.won?'Schicht geschafft! Zurück nach Hause. Neue Kolleg:innen können verfügbar sein.':'Schicht gescheitert. Zurück nach Hause.');render()}
});
render();
