import { loadMeta, saveMeta, saveRun } from './core/save.js';
import { RunController } from './core/run.js';
import { SKILLS, CHAR_DEFS, COMPANION_PROFILES, CHARACTER_SKILL_TREES } from './data/battle-data.js';

const partyStyle=document.createElement('link');partyStyle.rel='stylesheet';partyStyle.href=new URL('./party.css',import.meta.url).href;document.head.appendChild(partyStyle);
const meta=loadMeta(),app=document.querySelector('#app');
const controller=new RunController({meta,onMetaChange:saveMeta,onRunChange:run=>{saveRun(run);render()}});
let hubView='home',selectedCharacter='olivia';
const button=(label,action,extra='')=>`<button data-action="${action}" ${extra}>${label}</button>`;

function availableCharacterIds(){return ['olivia',...(meta.unlocks.companions||[])]}
function charProgress(id){return meta.characters[id]}
function canUnlockCharacterSkill(id,node){const p=charProgress(id);return !!p&&!p.unlocked.includes(node.id)&&node.req.every(req=>p.unlocked.includes(req))&&p.skillPoints>=node.cost}
function unlockCharacterSkill(id,skillId){const tree=CHARACTER_SKILL_TREES[id]||[],node=tree.find(n=>n.id===skillId),p=charProgress(id);if(!node||!p||!canUnlockCharacterSkill(id,node))return;p.skillPoints-=node.cost;p.unlocked.push(skillId);if(id==='olivia')meta.unlocks.skills=[...new Set([...(meta.unlocks.skills||[]),skillId])];saveMeta(meta);render()}
function renderCharacterManager(id){const c=CHAR_DEFS[id],p=charProgress(id),tree=CHARACTER_SKILL_TREES[id]||[],level=p?.level||1,maxHp=c.base.hp+(level-1)*6,maxMp=c.base.mp+(level-1)*3,atk=c.base.atk+(level-1)*2,def=c.base.def+(level-1),spd=c.base.spd+(level-1);const nodes=tree.map(node=>{const s=SKILLS[node.id],owned=p.unlocked.includes(node.id),available=canUnlockCharacterSkill(id,node);return `<article class="skill-node ${owned?'owned':available?'available':'locked'}"><span>Tier ${node.tier} · ${node.branch}</span><h3>${s.name}</h3><p>${s.desc}</p><small>${owned?'Freigeschaltet ✔':`${node.cost} SP · Voraussetzung: ${node.req.length?node.req.map(x=>SKILLS[x]?.name||x).join(', '):'keine'}`}</small>${owned?'':`<button data-char-skill="${id}:${node.id}" ${available?'':'disabled'}>Für ${node.cost} SP lernen</button>`}</article>`}).join('');return `<div class="character-sheet"><div class="character-title"><span class="big-avatar">${c.emoji}</span><div><h2>${c.name}</h2><p>${c.role}</p></div><strong>${p.skillPoints} SP</strong></div><div class="char-stats"><span>Level <b>${level}</b></span><span>EP <b>${p.xp}/${p.xpNext}</b></span><span>HP <b>${maxHp}</b></span><span>MP <b>${maxMp}</b></span><span>ATK <b>${atk}</b></span><span>DEF <b>${def}</b></span><span>SPD <b>${spd}</b></span></div><h3>Skilltree</h3><div class="skill-grid">${nodes}</div></div>`}
function renderPartyBuilder(){if(!availableCharacterIds().includes(selectedCharacter))selectedCharacter='olivia';const selected=new Set(meta.partySelection||[]);const tabs=availableCharacterIds().map(id=>{const c=CHAR_DEFS[id];return `<button class="char-tab ${selectedCharacter===id?'active':''}" data-char-tab="${id}">${c.emoji} ${c.name}<small>Lv${charProgress(id)?.level||1}</small></button>`}).join('');const cards=Object.keys(COMPANION_PROFILES).map(id=>{const c=CHAR_DEFS[id],p=COMPANION_PROFILES[id],unlocked=meta.unlocks.companions.includes(id),chosen=selected.has(id),cp=charProgress(id);return `<article class="companion-card ${chosen?'chosen':''} ${unlocked?'':'locked'}"><div class="companion-head"><span class="companion-avatar">${c.emoji}</span><div><h3>${c.name}</h3><small>${c.role} · Lv${cp?.level||1}</small></div></div><p>${p.tagline}</p>${unlocked?`<button data-companion="${id}">${chosen?'Aus Party entfernen':'In Party aufnehmen'}</button>`:`<div class="unlock-note">🔒 ${p.unlock}</div>`}</article>`}).join('');app.innerHTML=`<section class="panel apartment"><div class="eyebrow">PARTY & CHARAKTERE</div><h1>👥 Dienstplan</h1><p>Olivia ist immer gesetzt. Wähle bis zu vier Begleiter und verwalte hier gleichzeitig Level, EP und Skillpunkte aller freigeschalteten Figuren.</p><div class="party-cap"><b>🧠 Olivia</b><span>+ ${selected.size}/4 Begleiter gewählt</span></div><h2>Aktive Party</h2><div class="companion-grid">${cards}</div><h2>Charakterverwaltung</h2><div class="char-tabs">${tabs}</div>${renderCharacterManager(selectedCharacter)}<div class="actions">${button('← Zurück zur Wohnung','hub-home')}</div></section>`}
function renderHub(){if(hubView==='party'){renderPartyBuilder();return}const selectedNames=(meta.partySelection||[]).map(id=>CHAR_DEFS[id]?.name).filter(Boolean);app.innerHTML=`<section class="panel apartment"><div class="eyebrow">ROGUELITE v0.5 · DEV</div><h1>🏠 Olivias Wohnung</h1><p>Feierabend. In der Wohnung stellst du dein Team zusammen und entwickelst die Figuren dauerhaft weiter.</p><div class="stats"><div><span>Forschungsnotizen</span><strong>📚 ${meta.currency.notes}</strong></div><div><span>Gestartete Schichten</span><strong>${meta.stats.runsStarted}</strong></div><div><span>Gewonnene Schichten</span><strong>${meta.stats.runsWon}</strong></div><div><span>Verfügbare Figuren</span><strong>${1+meta.unlocks.companions.length}/5</strong></div></div><div class="party-preview"><span>Aktuelle Party</span><strong>🧠 Olivia${selectedNames.length?' + '+selectedNames.join(' + '):' · solo'}</strong></div><div class="room-grid"><article>🛏️ <b>Bett</b><small>Nächste Schicht / Story</small></article><article>💻 <b>Schreibtisch</b><small>Forschung & spätere Hub-Upgrades</small></article><article class="clickable" data-action="hub-party">👥 <b>Party</b><small>Team, Level, EP & Skillpunkte</small></article><article>☕ <b>Küche</b><small>Vorbereitung</small></article></div><div class="actions">${button('Schicht beginnen →','start')}</div></section>`}
function renderReward(run){const cards=run.pendingReward.map(r=>`<button class="reward-card" data-reward="${r.id}"><span>${r.icon||'✨'}</span><b>${r.name}</b><small>${r.text}</small></button>`).join('');return `<div class="reward-pick"><div class="eyebrow">SCHICHT-UPGRADE</div><h2>Wähle 1 von 3</h2><p>Diese Verbesserung gilt nur für die aktuelle Schicht.</p><div class="reward-grid">${cards}</div></div>`}
function renderRun(){const run=controller.run,room=controller.currentRoom(),route=run.route.map((r,i)=>`<div class="node ${i<run.roomIndex?'done':''} ${i===run.roomIndex?'current':''}"><span>${i+1}</span><b>${r.title}</b><small>${r.type}</small></div>`).join(''),party=run.party.map(c=>`<div class="run-party-card"><b style="color:${c.color}">${c.emoji} ${c.name}</b><small>Lv${c.level} · HP ${c.hp}/${c.maxHp} · MP ${c.mp}/${c.maxMp} · ${c.skillPoints} SP</small></div>`).join(''),relics=run.relics.length?run.relics.join(' · '):'noch keine';app.innerHTML=`<section class="panel hospital"><div class="eyebrow">AKTUELLE SCHICHT</div><h1>🏥 Klinikum</h1><p>Run ${run.id} · Raum ${Math.min(run.roomIndex+1,8)}/8 · ☕ ${run.resources.coffee}</p><div class="run-party">${party}</div><p class="relic-line"><b>Run-Upgrades:</b> ${relics}</p>${run.pendingReward?renderReward(run):`<div class="route">${route}</div><div class="encounter"><h2>${room?room.title:'Schicht abgeschlossen'}</h2><p>${room?room.type.toUpperCase():''}</p>${room?button(room.type==='event'?'Event betreten':'JRPG-Kampf betreten','enter'):''}</div>`}<p class="note">v0.5: persistente Charakterlevel, Skillpunkte, Partyverwaltung und individuelle Skilltrees.</p></section>`}
function render(){controller.run?renderRun():renderHub()}
function toggleCompanion(id){if(!meta.unlocks.companions.includes(id))return;const current=new Set(meta.partySelection||[]);if(current.has(id))current.delete(id);else{if(current.size>=4)return;current.add(id)}meta.partySelection=[...current];saveMeta(meta);render()}
document.addEventListener('click',async e=>{const charSkill=e.target.closest('[data-char-skill]')?.dataset.charSkill;if(charSkill){const [id,skillId]=charSkill.split(':');unlockCharacterSkill(id,skillId);return}const tab=e.target.closest('[data-char-tab]')?.dataset.charTab;if(tab){selectedCharacter=tab;render();return}const companion=e.target.closest('[data-companion]')?.dataset.companion;if(companion){toggleCompanion(companion);return}const reward=e.target.closest('[data-reward]')?.dataset.reward;if(reward){controller.chooseReward(reward);return}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='hub-party'){hubView='party';render();return}if(action==='hub-home'){hubView='home';render();return}if(action==='start'){hubView='home';controller.start();return}if(action==='enter'){const result=await controller.enterCurrentRoom();if(result?.kind==='run-finished')alert(result.won?'Schicht geschafft! EP und Skillpunkte wurden gespeichert.':'Schicht gescheitert. Erspielte Charakterfortschritte bleiben erhalten.');render()}});render();
