import { EQUIPMENT, EQUIPMENT_SLOTS, inventoryCounts, equippedCounts, availableCopies, canEquip } from './data/equipment.js';
import { CHAR_DEFS } from './data/battle-data.js';

const rarityLabel={common:'Gewöhnlich',uncommon:'Ungewöhnlich',rare:'Selten',epic:'Episch',legendary:'Legendär'};
const rarityIcon={common:'○',uncommon:'◇',rare:'◆',epic:'✦',legendary:'★'};

function wearerNames(meta,itemId){return Object.entries(meta.characters||{}).filter(([,p])=>Object.values(p.equipment||{}).includes(itemId)).map(([id])=>CHAR_DEFS[id]?.name||id);}
function itemCard(meta,itemId,count){const item=EQUIPMENT[itemId];if(!item)return '';const worn=equippedCounts(meta)[itemId]||0,free=Math.max(0,count-worn),wearers=wearerNames(meta,itemId);return `<article class="wardrobe-item rarity-${item.rarity||'common'}"><div class="wardrobe-item-icon">${item.icon}</div><div class="wardrobe-item-copy"><div class="wardrobe-item-head"><b>${item.name}</b><span>${rarityIcon[item.rarity||'common']} ${rarityLabel[item.rarity||'common']}</span></div><small>${EQUIPMENT_SLOTS[item.slot]}${item.owner?` · nur ${CHAR_DEFS[item.owner]?.name||item.owner}`:''}</small><p>${item.desc}</p><div class="wardrobe-counts"><span>Besitz <b>${count}</b></span><span>Ausgerüstet <b>${worn}</b></span><span>Frei <b>${free}</b></span></div>${wearers.length?`<small class="wardrobe-wearer">👤 ${wearers.join(', ')}</small>`:''}</div></article>`}

export function renderWardrobe(meta){const counts=inventoryCounts(meta.unlocks?.equipment||[]),ids=Object.keys(counts).filter(id=>EQUIPMENT[id]);const bySlot=Object.keys(EQUIPMENT_SLOTS).map(slot=>{const slotIds=ids.filter(id=>EQUIPMENT[id].slot===slot);return `<section class="wardrobe-shelf"><h2>${EQUIPMENT_SLOTS[slot]}</h2>${slotIds.length?`<div class="wardrobe-grid">${slotIds.map(id=>itemCard(meta,id,counts[id])).join('')}</div>`:'<p>Noch keine Gegenstände in diesem Fach.</p>'}</section>`}).join('');return `<section class="panel apartment wardrobe-window"><div class="eyebrow">OLIVIAS KLEIDERSCHRANK</div><h1>🚪 Kleiderschrank & Inventar</h1><p>Hier liegt die permanente Ausrüstung der Gruppe. Jedes Exemplar existiert nur so oft, wie es im Inventar vorhanden ist.</p><div class="wardrobe-rule">🔒 <b>Inventarregel:</b> 1 Exemplar = maximal 1 gleichzeitig ausgerüsteter Charakter. Mehrfachvergabe ist nur bei mehreren Exemplaren möglich.</div><div class="wardrobe-summary"><span>Verschiedene Gegenstände <b>${ids.length}</b></span><span>Exemplare gesamt <b>${Object.values(counts).reduce((a,b)=>a+b,0)}</b></span><span>Davon ausgerüstet <b>${Object.values(equippedCounts(meta)).reduce((a,b)=>a+b,0)}</b></span></div>${bySlot}<div class="actions"><button data-action="hub-home">← Zurück zur Wohnung</button></div></section>`}

export function equipmentChoices(meta,characterId,slot){const counts=inventoryCounts(meta.unlocks?.equipment||[]);return Object.keys(counts).map(id=>EQUIPMENT[id]).filter(item=>item&&item.slot===slot&&canEquip(characterId,item)&&(availableCopies(meta,item.id)>0||meta.characters?.[characterId]?.equipment?.[slot]===item.id));}
