import { ENEMY_TEMPLATES, ENCOUNTERS, SKILLS } from '../data/battle-data.js';
function enemyInstance(id,depth,index){const t=ENEMY_TEMPLATES[id],mult=1+(Math.max(1,depth)-1)*.10;return {uid:`${id}-${index}-${Math.random().toString(36).slice(2,6)}`,name:t.name,emoji:t.emoji,boss:!!t.boss,maxHp:Math.round(t.hp*mult),hp:Math.round(t.hp*mult),atk:Math.round(t.atk*mult),def:Math.round(t.def*mult),spd:t.spd,xp:Math.round(t.xp*mult),stunned:false,defDown:false}}
const living=list=>list.filter(x=>x.hp>0),clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
export function startJRPGCombat({encounter,party,run}){
 const host=document.querySelector('#battle-layer');if(!host)throw new Error('Missing #battle-layer');
 const enemyIds=encounter.enemies||ENCOUNTERS[encounter.id]||['verwirrter_patient'];
 const state={encounter,party,enemies:enemyIds.map((id,i)=>enemyInstance(id,(run?.roomIndex||0)+1,i)),turnQueue:[],currentActor:null,selection:null,log:'Der Kampf beginnt!',over:false,coffee:run?.resources?.coffee??1};
 let resolver;const resultPromise=new Promise(resolve=>resolver=resolve);host.classList.remove('hidden');host.innerHTML=battleShell(encounter);
 const partyAlive=()=>living(state.party),enemiesAlive=()=>living(state.enemies),has=id=>(run?.relics||[]).includes(id),hasSyn=id=>(run?.synergies||[]).includes(id),member=id=>state.party.find(c=>c.id===id);
 function message(text){state.log=text;const el=host.querySelector('#v2-battle-log');if(el)el.textContent=text}
 function render(){const enemies=host.querySelector('#v2-enemies');enemies.innerHTML=state.enemies.map(e=>`<button class="v2-enemy ${e.hp<=0?'dead':''} ${e.boss?'boss':''}" data-enemy="${e.uid}" ${e.hp<=0?'disabled':''}><span class="sprite">${e.emoji}</span><b>${e.name}</b>${e.defDown?'<small>🩻 DEF ↓</small>':''}${e.stunned?'<small>💤 betäubt</small>':''}<span class="meter"><i style="width:${clamp(e.hp/e.maxHp*100,0,100)}%"></i></span><small>${e.hp}/${e.maxHp} HP</small></button>`).join('');const partyEl=host.querySelector('#v2-party');partyEl.innerHTML=state.party.map(c=>`<button class="v2-pcard ${c.hp<=0?'dead':''} ${state.currentActor===c.id?'turn':''}" data-ally="${c.id}" ${c.hp<=0?'disabled':''}><b style="color:${c.color}">${c.emoji} ${c.name} · Lv${c.level}</b><small>HP ${c.hp}/${c.maxHp}</small><span class="meter hp"><i style="width:${clamp(c.hp/c.maxHp*100,0,100)}%"></i></span><small>MP ${c.mp}/${c.maxMp}</small><span class="meter mp"><i style="width:${clamp(c.mp/c.maxMp*100,0,100)}%"></i></span></button>`).join('');message(state.log)}
 function menu(html){host.querySelector('#v2-battle-menu').innerHTML=html}
 function mainMenu(actor){menu(`<div class="v2-menu-row"><button data-cmd="attack">⚔️ Angriff</button><button data-cmd="skills">✨ Fähigkeit</button><button data-cmd="defend">🛡️ Verteidigen</button><button data-cmd="coffee" ${state.coffee<=0?'disabled':''}>☕ Kaffee ×${state.coffee}</button></div>`);bindCommandButtons(actor)}
 function bindCommandButtons(actor){host.querySelector('[data-cmd="attack"]')?.addEventListener('click',()=>target(actor,{id:'basic',name:'Angriff',mp:0,type:'dmg',power:1,target:'single'}));host.querySelector('[data-cmd="skills"]')?.addEventListener('click',()=>skillMenu(actor));host.querySelector('[data-cmd="defend"]')?.addEventListener('click',()=>{const bonus=Math.max(1,Math.round(actor.base.def*.5));actor.def+=bonus;actor._guardBonus=bonus;message(`${actor.name} verteidigt.`);endPlayerTurn()});host.querySelector('[data-cmd="coffee"]')?.addEventListener('click',()=>{if(state.coffee<=0)return;state.coffee--;if(run?.resources)run.resources.coffee=state.coffee;actor.mp=Math.min(actor.maxMp,actor.mp+10);message(`${actor.name} trinkt Kaffee. MP +10.`);render();endPlayerTurn()})}
 function skillMenu(actor){const buttons=actor.unlocked.map(id=>SKILLS[id]).filter(Boolean).map(s=>`<button data-skill="${s.id}" ${actor.mp<s.mp?'disabled':''}><b>${s.name}</b><small>MP ${s.mp} · ${s.desc}</small></button>`).join('');menu(`<div class="v2-skill-list">${buttons}<button data-cmd="back">◀ Zurück</button></div>`);host.querySelectorAll('[data-skill]').forEach(btn=>btn.addEventListener('click',()=>target(actor,SKILLS[btn.dataset.skill])));host.querySelector('[data-cmd="back"]')?.addEventListener('click',()=>mainMenu(actor))}
 function target(actor,skill){if(actor.mp<skill.mp)return;if(skill.target==='party'||skill.target==='all'){execute(actor,skill,null);return}state.selection={actor,skill};const hostile=['dmg','dmg_all','debuff_def','stun'].includes(skill.type);message(hostile?'Ziel wählen: Gegner anklicken.':'Ziel wählen: Verbündete/n anklicken.');menu('<div class="v2-target-hint">Ziel auswählen …</div>');render()}
 function damageMultiplier(actor,skill,targetEntity){let mult=1;if(skill.id==='reflexhammer'&&has('reflex-routine'))mult*=1.25;if(has('night-focus')&&actor.hp/actor.maxHp<.5)mult*=1.30;if(hasSyn('neuro_internal')&&targetEntity?.defDown)mult*=1.10;if(hasSyn('neuro_anaesthesia')&&actor.id==='olivia'&&targetEntity?.stunned)mult*=1.30;const olivia=member('olivia');if(hasSyn('neuro_trauma')&&actor.id==='tobi'&&olivia&&olivia.hp/olivia.maxHp<.5)mult*=1.20;return mult}
 function healMultiplier(actor,targetEntity){let mult=1;if(has('steady-hands'))mult*=1.25;if(actor.id==='lisa'&&actor.unlocked.includes('stationsruhe'))mult*=1.15;if(hasSyn('neuro_internal'))mult*=1.10;if(hasSyn('shock_room')&&actor.id==='lisa'&&targetEntity?.id==='tobi')mult*=1.20;return mult}
 function execute(actor,skill,targetEntity){actor.mp-=skill.mp;state.selection=null;switch(skill.type){case 'dmg':{let dmg=Math.max(1,Math.round(actor.atk*skill.power*damageMultiplier(actor,skill,targetEntity)-targetEntity.def*.5+(Math.random()*4-2)));const crit=Math.random()*100<(actor.crit||5);if(crit)dmg=Math.round(dmg*1.6);targetEntity.hp=Math.max(0,targetEntity.hp-dmg);message(`${actor.name} nutzt ${skill.name} auf ${targetEntity.name} – ${dmg} Schaden!${crit?' Kritischer Treffer! 💥':''}`);break}case 'dmg_all':enemiesAlive().forEach(e=>e.hp=Math.max(0,e.hp-Math.max(1,Math.round(actor.atk*skill.power*damageMultiplier(actor,skill,e)-e.def*.5))));message(`${actor.name} nutzt ${skill.name} – alle Gegner werden getroffen!`);break;case 'heal':{const heal=Math.round((actor.atk*.8*skill.power+10)*healMultiplier(actor,targetEntity));targetEntity.hp=Math.min(targetEntity.maxHp,targetEntity.hp+heal);message(`${actor.name} heilt ${targetEntity.name} um ${heal} HP.`);break}case 'heal_all':{const heal=Math.round((actor.atk*.7*skill.power+8)*healMultiplier(actor,null));partyAlive().forEach(c=>c.hp=Math.min(c.maxHp,c.hp+heal));message(`${actor.name} heilt die ganze Party um ${heal} HP.`);break}case 'buff_atk':{const amt=Math.round(actor.atk*skill.power)+2;partyAlive().forEach(c=>c.atk+=amt);message(`${actor.name} nutzt ${skill.name} – Angriff steigt!`);break}case 'buff_def':case 'buff_def_all':{const amt=Math.round((actor.def+3)*skill.power)+1;(skill.target==='party'?partyAlive():[targetEntity]).forEach(c=>c.def+=amt);message(`${actor.name} nutzt ${skill.name} – Verteidigung steigt!`);break}case 'debuff_def':{const amt=Math.round(targetEntity.def*skill.power)+1;targetEntity.def=Math.max(0,targetEntity.def-amt);targetEntity.defDown=true;message(`${actor.name} nutzt ${skill.name} – ${targetEntity.name}s Verteidigung sinkt!`);break}case 'stun':targetEntity.stunned=true;message(`${targetEntity.name} ist betäubt!`);break}render();endPlayerTurn()}
 function enemyAct(enemy){const targets=partyAlive();if(!targets.length)return;const t=targets[Math.floor(Math.random()*targets.length)];let dmg=Math.max(1,Math.round(enemy.atk-t.def*.5+(Math.random()*6-3)));if(has('quiet-call'))dmg=Math.max(1,Math.round(dmg*.9));t.hp=Math.max(0,t.hp-dmg);message(`${enemy.emoji} ${enemy.name} greift ${t.name} an – ${dmg} Schaden!`);render()}
 function buildQueue(){const all=[...partyAlive().map(c=>({kind:'player',ref:c,spd:c.spd})),...enemiesAlive().map(e=>({kind:'enemy',ref:e,spd:e.spd}))];all.sort((a,b)=>b.spd-a.spd);state.turnQueue=all}
 function checkEnd(){if(!enemiesAlive().length){finish('victory');return true}if(!partyAlive().length){finish('defeat');return true}return false}
 function processQueue(){if(state.over||checkEnd())return;if(!state.turnQueue.length){state.party.forEach(c=>{if(c._guardBonus){c.def=Math.max(c.base.def,c.def-c._guardBonus);delete c._guardBonus}});buildQueue()}const turn=state.turnQueue.shift();if(!turn?.ref||turn.ref.hp<=0){processQueue();return}if(turn.kind==='enemy'){if(turn.ref.stunned){turn.ref.stunned=false;message(`${turn.ref.name} ist betäubt und setzt aus.`);setTimeout(processQueue,350);return}enemyAct(turn.ref);setTimeout(processQueue,500);return}state.currentActor=turn.ref.id;render();mainMenu(turn.ref)}
 function endPlayerTurn(){state.currentActor=null;menu('');setTimeout(processQueue,350)}
 function awardXP(){const total=state.enemies.reduce((s,e)=>s+e.xp,0),base=Math.round(total/state.party.length)+5,gain=Math.round(base*(has('teaching-round')?1.2:1)),levels=[];state.party.forEach(c=>{c.xp+=gain;while(c.xp>=c.xpNext){c.xp-=c.xpNext;c.level++;c.xpNext=30+c.level*15;c.maxHp+=6;c.maxMp+=3;c.atk+=2;c.def+=1;c.spd+=1;c.skillPoints++;levels.push(`${c.name} → Level ${c.level}`)}c.hp=Math.min(c.maxHp,c.hp+Math.ceil(c.maxHp*.60));c.mp=Math.min(c.maxMp,c.mp+Math.ceil(c.maxMp*.60));c.buffs={atk:0,def:0,spd:0}});return {xp:gain,levels}}
 function finish(outcome){if(state.over)return;state.over=true;menu('');let rewards={notes:0,xp:0,levels:[]};if(outcome==='victory'){const xp=awardXP();rewards={notes:encounter.type==='boss'?5:encounter.type==='elite'?2:1,...xp};message(`Sieg! +${xp.xp} EP · Erholung 60 % HP/MP${rewards.notes?` · +${rewards.notes} Forschungsnotizen`:''}`)}else message('Die Schicht war zu viel. Olivia zieht sich zurück.');render();host.querySelector('#v2-battle-exit').classList.remove('hidden');host.querySelector('#v2-battle-exit').textContent=outcome==='victory'?'Weiter →':'Zurück zur Wohnung';host.querySelector('#v2-battle-exit').onclick=()=>{host.classList.add('hidden');host.innerHTML='';resolver({outcome,rewards,party:state.party})}}
 host.addEventListener('click',e=>{const enemyBtn=e.target.closest('[data-enemy]');if(enemyBtn&&state.selection){const enemy=state.enemies.find(x=>x.uid===enemyBtn.dataset.enemy);if(enemy&&['dmg','dmg_all','debuff_def','stun'].includes(state.selection.skill.type))execute(state.selection.actor,state.selection.skill,enemy);return}const allyBtn=e.target.closest('[data-ally]');if(allyBtn&&state.selection){const ally=state.party.find(x=>x.id===allyBtn.dataset.ally);if(ally&&!['dmg','dmg_all','debuff_def','stun'].includes(state.selection.skill.type))execute(state.selection.actor,state.selection.skill,ally)}});render();buildQueue();processQueue();return resultPromise;
}
function battleShell(encounter){return `<section class="v2-battle-panel"><div class="v2-battle-head"><div><span>JRPG-KAMPF · ${encounter.type.toUpperCase()}</span><h2>${encounter.title}</h2></div><button id="v2-battle-exit" class="hidden"></button></div><div id="v2-enemies" class="v2-enemies"></div><div id="v2-battle-log" class="v2-battle-log">Der Kampf beginnt!</div><div id="v2-party" class="v2-party"></div><div id="v2-battle-menu" class="v2-battle-menu"></div></section>`}
